/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

/**
 *
 * @author Home
 */
public class JFMenu extends javax.swing.JFrame {
    
    static boolean vCli=false;
    static boolean vPres=false;
    static boolean vCroCuo=false;
    static boolean vPag=false;
    static boolean vConCli=false;
    static boolean vRepCli=false;
    static boolean vRepCliD=false;
    static boolean vManCli=false;

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        dskPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnRegistroCliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnRegistroPrestamo = new javax.swing.JMenuItem();
        mnRegistroPago = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnGenerar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnConsultaCliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnReporteClientes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnReporteClientePrestamo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnMantenimientoClientes = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMAS DE PRESTAMOS \"LOS MOROSOS\"");

        javax.swing.GroupLayout dskPanelLayout = new javax.swing.GroupLayout(dskPanel);
        dskPanel.setLayout(dskPanelLayout);
        dskPanelLayout.setHorizontalGroup(
            dskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        dskPanelLayout.setVerticalGroup(
            dskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        mnRegistroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Acerca.gif"))); // NOI18N
        mnRegistroCliente.setText("Registro");
        mnRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegistroClienteActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Docente.gif"))); // NOI18N
        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnRegistroCliente.add(jMenuItem1);

        mnRegistroPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/icono_ayuda_msocios.gif"))); // NOI18N
        mnRegistroPrestamo.setText("Prestamo");
        mnRegistroPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegistroPrestamoActionPerformed(evt);
            }
        });
        mnRegistroCliente.add(mnRegistroPrestamo);

        mnRegistroPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/monedas.png"))); // NOI18N
        mnRegistroPago.setText("Pago");
        mnRegistroPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegistroPagoActionPerformed(evt);
            }
        });
        mnRegistroCliente.add(mnRegistroPago);

        jMenuBar1.add(mnRegistroCliente);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Reporte1.gif"))); // NOI18N
        jMenu2.setText("Cronograma");

        mnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Lista.gif"))); // NOI18N
        mnGenerar.setText("Generar");
        mnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGenerarActionPerformed(evt);
            }
        });
        jMenu2.add(mnGenerar);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Buscar2.gif"))); // NOI18N
        jMenu3.setText("Consulta");

        mnConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Docente.gif"))); // NOI18N
        mnConsultaCliente.setText("Cliente");
        mnConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultaClienteActionPerformed(evt);
            }
        });
        jMenu3.add(mnConsultaCliente);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Modificar.gif"))); // NOI18N
        jMenu4.setText("Reporte");

        mnReporteClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Docente.gif"))); // NOI18N
        mnReporteClientes.setText("Clientes");
        mnReporteClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReporteClientesActionPerformed(evt);
            }
        });
        jMenu4.add(mnReporteClientes);
        jMenu4.add(jSeparator1);

        mnReporteClientePrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Alumno.gif"))); // NOI18N
        mnReporteClientePrestamo.setText("Clientes (Prestamos Pendientes)");
        mnReporteClientePrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReporteClientePrestamoActionPerformed(evt);
            }
        });
        jMenu4.add(mnReporteClientePrestamo);

        jMenuBar1.add(jMenu4);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/colores.gif"))); // NOI18N
        jMenu1.setText("Mantenimiento");

        mnMantenimientoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Docente.gif"))); // NOI18N
        mnMantenimientoClientes.setText("Clientes");
        mnMantenimientoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMantenimientoClientesActionPerformed(evt);
            }
        });
        jMenu1.add(mnMantenimientoClientes);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegistroClienteActionPerformed
        
    }//GEN-LAST:event_mnRegistroClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(vCli==false){
        JIFRegistroCliente oCli= new JIFRegistroCliente();
        dskPanel.add(oCli);
        oCli.setVisible(true);
        vCli=true;
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnRegistroPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegistroPrestamoActionPerformed
        if(vPres==false){
        JIFRegistroPrestamo oPres= new JIFRegistroPrestamo();
        dskPanel.add(oPres);
        oPres.setVisible(true);
        vPres=true;
        }
    }//GEN-LAST:event_mnRegistroPrestamoActionPerformed

    private void mnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGenerarActionPerformed
        if(vCroCuo==false){
        JIFGenerarCronograma oCroCuo= new JIFGenerarCronograma();
        dskPanel.add(oCroCuo);
        oCroCuo.setVisible(true);
        vCroCuo=true;
        }
    }//GEN-LAST:event_mnGenerarActionPerformed

    private void mnRegistroPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegistroPagoActionPerformed
        if(vPag==false){
        JIFRegistroPago oPag= new JIFRegistroPago();
        dskPanel.add(oPag);
        oPag.setVisible(true);
        vPag=true;
        }
    }//GEN-LAST:event_mnRegistroPagoActionPerformed

    private void mnMantenimientoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMantenimientoClientesActionPerformed
        if(vManCli==false){
        JIFMantenimientoCliente oManCli= new JIFMantenimientoCliente();
        dskPanel.add(oManCli);
        oManCli.setVisible(true);
        vManCli=true;
        }
    }//GEN-LAST:event_mnMantenimientoClientesActionPerformed

    private void mnConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultaClienteActionPerformed
        if(vConCli==false){
        JIFConsultaCliente oConCli= new JIFConsultaCliente();
        dskPanel.add(oConCli);
        oConCli.setVisible(true);
        vConCli=true;
        }
    }//GEN-LAST:event_mnConsultaClienteActionPerformed

    private void mnReporteClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReporteClientesActionPerformed
        if(vRepCli==false){
        JIFReporteCliente oRepCli= new JIFReporteCliente();
        dskPanel.add(oRepCli);
        oRepCli.setVisible(true);
        vRepCli=true;
        }
    }//GEN-LAST:event_mnReporteClientesActionPerformed

    private void mnReporteClientePrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReporteClientePrestamoActionPerformed
        if(vRepCliD==false){
        JIFReporteClienteDeuda oRepCliD= new JIFReporteClienteDeuda();
        dskPanel.add(oRepCliD);
        oRepCliD.setVisible(true);
        vRepCliD=true;
        }
    }//GEN-LAST:event_mnReporteClientePrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnConsultaCliente;
    private javax.swing.JMenuItem mnGenerar;
    private javax.swing.JMenuItem mnMantenimientoClientes;
    private javax.swing.JMenu mnRegistroCliente;
    private javax.swing.JMenuItem mnRegistroPago;
    private javax.swing.JMenuItem mnRegistroPrestamo;
    private javax.swing.JMenuItem mnReporteClientePrestamo;
    private javax.swing.JMenuItem mnReporteClientes;
    // End of variables declaration//GEN-END:variables
}
