/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.ClienteJuridico;
import entidades.ClienteNatural;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class JIFMantenimientoCliente extends javax.swing.JInternalFrame {
    
    ClienteNatural cn = null;
    ClienteJuridico cj = null;

    /**
     * Creates new form JIFMantenimientoCliente
     */
    public JIFMantenimientoCliente() {
        initComponents();
    }
    
    public void limpiar(){
        txtNombres.setText(null);
        txtClienteCorreo.setText(null);
        txtClienteDireccion.setText(null);
        txtClienteTelefono.setText(null);
        txtClientePerContacto.setText(null);
        txtClienteLabor.setText(null);
        
        txtNombres.setEnabled(false);
        txtClienteCorreo.setEnabled(false);
        txtClienteDireccion.setEnabled(false);
        txtClienteTelefono.setEnabled(false);
        txtClientePerContacto.setEnabled(false);
        txtClienteLabor.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtClienteLabor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtClienteTelefono = new javax.swing.JTextField();
        txtClientePerContacto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtClienteDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtClienteCorreo = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Mantenimiento Cliente");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Buscar2.gif"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombres:");

        txtNombres.setBackground(new java.awt.Color(240, 240, 240));
        txtNombres.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombres.setDoubleBuffered(true);
        txtNombres.setEnabled(false);

        jLabel1.setText("Codigo:");

        jLabel8.setText("Labor:");

        txtClienteLabor.setEnabled(false);
        txtClienteLabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteLaborActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefono:");

        jLabel9.setText("Nombre Persona de Contacto:");

        txtClienteTelefono.setEnabled(false);
        txtClienteTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteTelefonoActionPerformed(evt);
            }
        });

        txtClientePerContacto.setEnabled(false);
        txtClientePerContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientePerContactoActionPerformed(evt);
            }
        });

        jLabel5.setText("Dirección:");

        txtClienteDireccion.setEnabled(false);

        jLabel6.setText("Correo:");

        txtClienteCorreo.setEnabled(false);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/cancel.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Modificar.gif"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Eliminar.gif"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(1, 1, 1))
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtClienteDireccion)
                            .addComponent(txtClienteCorreo)
                            .addComponent(txtClienteTelefono)
                            .addComponent(txtClienteLabor)
                            .addComponent(txtClientePerContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(txtNombres))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnEliminar)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir)
                            .addComponent(btnBuscar))))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtClienteCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteLabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtClientePerContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String dni = txtDNI.getText();
        int k=-1;

        if(dni.length()!=0){

            for(int i=0;i<JIFRegistroCliente.cli.getCNaturales().size();i++){
                if(dni.equals(JIFRegistroCliente.cli.getCNaturales().get(i).getCodigo())){
                    cn = JIFRegistroCliente.cli.getCNaturales().get(i);
                    txtNombres.setText(JIFRegistroCliente.cli.getCNaturales().get(i).getNombre());
                    txtClienteCorreo.setText(JIFRegistroCliente.cli.getCNaturales().get(i).getCorreo());
                    txtClienteDireccion.setText(JIFRegistroCliente.cli.getCNaturales().get(i).getDireccion());
                    txtClienteLabor.setText(JIFRegistroCliente.cli.getCNaturales().get(i).getLabor());
                    txtClienteTelefono.setText(JIFRegistroCliente.cli.getCNaturales().get(i).getTelefono());
                    txtClienteLabor.setEnabled(true);
                    txtClientePerContacto.setEnabled(false);
                    txtClientePerContacto.setText(null);
                    k=0;
                    txtNombres.setEnabled(true);
                    txtClienteCorreo.setEnabled(true);
                    txtClienteDireccion.setEnabled(true);
                    txtClienteTelefono.setEnabled(true);
                }
            }

            for(int i=0;i<JIFRegistroCliente.cli.getCJuridicos().size();i++){
                if(dni.equals(JIFRegistroCliente.cli.getCJuridicos().get(i).getCodigo())){
                    cj = JIFRegistroCliente.cli.getCJuridicos().get(i);
                    txtNombres.setText(JIFRegistroCliente.cli.getCJuridicos().get(i).getNombre());
                    txtClienteCorreo.setText(JIFRegistroCliente.cli.getCJuridicos().get(i).getCorreo());
                    txtClienteDireccion.setText(JIFRegistroCliente.cli.getCJuridicos().get(i).getDireccion());
                    txtClienteTelefono.setText(JIFRegistroCliente.cli.getCJuridicos().get(i).getTelefono());
                    txtClientePerContacto.setText(JIFRegistroCliente.cli.getCJuridicos().get(i).getPersonaDeContacto());
                    txtClienteLabor.setEnabled(false);
                    txtClienteLabor.setText(null);
                    txtClientePerContacto.setEnabled(true);
                    k=0;
                    txtNombres.setEnabled(true);
                    txtClienteCorreo.setEnabled(true);
                    txtClienteDireccion.setEnabled(true);
                    txtClienteTelefono.setEnabled(true);
                }

            }
            if(k==-1){
                JOptionPane.showMessageDialog(this, "No hay un cliente registrado con este código", "Regresar", 1);
                limpiar();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese un codigo", "Regresar", 1);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtClienteLaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteLaborActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteLaborActionPerformed

    private void txtClienteTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteTelefonoActionPerformed

    private void txtClientePerContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientePerContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientePerContactoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        JFMenu.vManCli=false;
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        JFMenu.vManCli=false;
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try{
            String dni = txtDNI.getText();

            if(dni.length()!=0){

                if(txtNombres.getText().length()!=0){
                    
                    if(dni.length()==8){
                        
                        cn.setCodigo(txtDNI.getText());
                        cn.setNombre(txtNombres.getText());
                        cn.setTelefono(txtClienteTelefono.getText());
                        cn.setCorreo(txtClienteCorreo.getText());
                        cn.setLabor(txtClienteLabor.getText());
                        cn.setDireccion(txtClienteDireccion.getText());
                        JOptionPane.showMessageDialog(this, "Cliente Modificado", "Regresar", 1);
                        limpiar();
                    }
                    
                    else{
                        if(dni.length()==11){
                            cj.setCodigo(txtDNI.getText());
                            cj.setNombre(txtNombres.getText());
                            cj.setTelefono(txtClienteTelefono.getText());
                            cj.setCorreo(txtClienteCorreo.getText());
                            cj.setPersonaDeContacto(txtClientePerContacto.getText());
                            cj.setDireccion(txtClienteDireccion.getText());
                            JOptionPane.showMessageDialog(this, "Cliente Modificado", "Regresar", 1);
                            limpiar();
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Ingrese un Código válido", "Regresar", 1);
                        }
                    }
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Ingrese un cliente", "Regresar", 1);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Ingrese un codigo", "Regresar", 1);
            }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Ingrese valores requeridos", "Regresar", 1);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try{
            String dni = txtDNI.getText();

            if(dni.length()!=0){

                if(txtNombres.getText().length()!=0){
                    
                    if(dni.length()==8){
                        JIFRegistroCliente.cli.eliminarClienteN(dni);
                        JOptionPane.showMessageDialog(this, "Cliente Eliminado", "Regresar", 1);
                        limpiar();
                    }
                    else{
                        if(dni.length()==11){
                            JIFRegistroCliente.cli.eliminarClienteJ(dni);
                            JOptionPane.showMessageDialog(this, "Cliente Eliminado", "Regresar", 1);
                            limpiar();
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Ingrese un Código válido", "Regresar", 1);
                        }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Ingrese un cliente", "Regresar", 1);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Ingrese un codigo", "Regresar", 1);
            }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Ingrese valores requeridos", "Regresar", 1);
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtClienteCorreo;
    private javax.swing.JTextField txtClienteDireccion;
    private javax.swing.JTextField txtClienteLabor;
    private javax.swing.JTextField txtClientePerContacto;
    private javax.swing.JTextField txtClienteTelefono;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
