/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.*;
import entidades.*;
import accesoDatos.*;
import java.util.*;

/**
 *
 * @author Home
 */
public class JIFRegistroPrestamo extends javax.swing.JInternalFrame {
    
    static BaseDatosPrestamo BPres = new BaseDatosPrestamo();
    Prestamo Pres=null;
    Calendar fechaHoy = Calendar.getInstance();
    Calendar fechaPagos = Calendar.getInstance();
    
    public void sumarMes(Calendar f,int n){
        f.add(Calendar.MONTH, n);
    }
    
    public void editarFecha(int anio,int mes, int dia){
        fechaPagos.set(anio, mes, dia);
    }
    
    public void diaDelMes(Calendar f,int n){
        int dia = fechaHoy.get(Calendar.DATE);
        if(dia>=n){
            f.set(f.get(Calendar.YEAR),f.get(Calendar.MONTH), n);
            sumarMes(f,1);
        }
        else{
            f.set(f.get(Calendar.YEAR),f.get(Calendar.MONTH), n);
        }
    }
    
    public void limpiar(){
        txtDNI.setText(null);
        txtInteres.setText("0");
        txtMonto.setText("0");
        txtNombres.setText(null);
        cmbDiaPago.setSelectedIndex(0);
        cmbCuotas.setSelectedIndex(1);
    }

    /**
     * Creates new form JIFRegistroPrestamo
     */
    public JIFRegistroPrestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtInteres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbCuotas = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtFechaEmision = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbDiaPago = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Resgistro Prestamo");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Codigo:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Buscar2.gif"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombres:");

        txtNombres.setBackground(new java.awt.Color(204, 204, 204));
        txtNombres.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombres.setDoubleBuffered(true);
        txtNombres.setEnabled(false);

        jLabel3.setText("Monto:");

        jLabel4.setText("Interes:");

        jLabel5.setText("Cuotas:");

        cmbCuotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "12", "18", "24", "30", "36" }));
        cmbCuotas.setSelectedIndex(1);
        cmbCuotas.setToolTipText("");
        cmbCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCuotasActionPerformed(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Modificar.gif"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/cancel.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha de Emisión:");

        txtFechaEmision.setEnabled(false);
        txtFechaEmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaEmisionActionPerformed(evt);
            }
        });

        jLabel7.setText("Días de Pago:");

        cmbDiaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtInteres)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)))
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbCuotas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaEmision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(cmbDiaPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbDiaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnSalir))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuotasActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try{
        
        Cliente c = null;
        Calendar fechaPago = Calendar.getInstance();
        fechaPago.add(Calendar.MONTH, 1);
        Calendar fechaux = Calendar.getInstance();
        fechaux.add(Calendar.MONTH, 1);
        String dni = txtDNI.getText();
        int cuotas = Integer.parseInt((String)cmbCuotas.getSelectedItem());
        float monto = Float.parseFloat(txtMonto.getText()), interes = Float.parseFloat(txtInteres.getText());
        int dia = cmbDiaPago.getSelectedIndex()+1;
        boolean estado = false;
        
        if(dni.length()!=0){
        
        if(txtNombres.getText().length()!=0){
        
        if(interes>0&&monto>0){
            int k=0;
            for(int i=0;i<JIFRegistroCliente.cli.getClientes().size();i++){
                if(dni.equals(JIFRegistroCliente.cli.getClientes().get(i).getCodigo())){
                    c = JIFRegistroCliente.cli.getClientes().get(i);
                }
            }
            
            for(int i=0;i<BPres.getPrestamos().size();i++){
                if(c==BPres.getPrestamos().get(i).getCliente()){
                    if(BPres.getPrestamos().get(i).isEstado()==false){
                        k=1;
                    }
                }
            }
            
            if(k==0){
                diaDelMes(fechaPago,dia);
                diaDelMes(fechaux,dia);
                Pres = new Prestamo(c,monto,interes,cuotas,fechaPago,estado);
                BPres.agregarPrestamo(Pres);
                
                float interPrc = interes/100;
                double interTot = Math.pow((1+interPrc),cuotas);
                
                float cuotaFija =(float)(monto*((interPrc*interTot)/(interTot-1)));
                
                int nCuota=1;
                float interesCuota=monto*(interes/100),saldoCuota=monto,amortizacionCuota=cuotaFija-interesCuota;
                boolean estadoCuota = false;
                sumarMes(fechaux,-1);
                Date fechaaa = fechaux.getTime();
                
                for(int i=0;i<cuotas;i++){
                    Cuota cuota = new Cuota(Pres,nCuota,saldoCuota,amortizacionCuota,interesCuota,cuotaFija,fechaaa,estadoCuota);
                    JIFGenerarCronograma.BCuota.agregarCuota(cuota);
                    
                    nCuota++;
                    saldoCuota=saldoCuota-amortizacionCuota;
                    interesCuota=saldoCuota*(interes/100);
                    amortizacionCuota=cuotaFija-interesCuota;
                    sumarMes(fechaux,1);
                    fechaaa = fechaux.getTime();
                }
                
                JOptionPane.showMessageDialog(this, "Prestamo registrado", "Regresar", 1);
                limpiar();
                
            }
            else{
                JOptionPane.showMessageDialog(this, "El cliente tiene un prestamo pendiente", "Regresar", 1);
                limpiar();
            }
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Ingrese un interes y/o monto válido", "Regresar", 1);
        }
        
        }
        else{
            JOptionPane.showMessageDialog(this, "Ingrese un cliente", "Regresar", 1);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "Ingrese un codigo", "Regresar", 1);
        }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Ingrese valores requeridos", "Regresar", 1);
            txtMonto.setText("0");
            txtInteres.setText("0");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String dni = txtDNI.getText();
        int k=-1;
        
        if(dni.length()!=0){
        
        for(int i=0;i<JIFRegistroCliente.cli.getCNaturales().size();i++){
            if(dni.equals(JIFRegistroCliente.cli.getCNaturales().get(i).getCodigo())){
                txtNombres.setText(JIFRegistroCliente.cli.getCNaturales().get(i).getNombre());
                k=0;
            }
        }    

        for(int i=0;i<JIFRegistroCliente.cli.getCJuridicos().size();i++){
            if(dni.equals(JIFRegistroCliente.cli.getCJuridicos().get(i).getCodigo())){
                txtNombres.setText(JIFRegistroCliente.cli.getCJuridicos().get(i).getNombre());
                k=0;
            }
        }
        
        if(k==-1){
                JOptionPane.showMessageDialog(this, "No hay un cliente registrado con este código", "Regresar", 1);
                limpiar();
        }
        
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese un codigo", "Regresar", 1);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        JFMenu.vPres=false;
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        JFMenu.vPres=false;
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        sumarMes(fechaHoy,1);
        txtMonto.setText("0");
        txtInteres.setText("0");
        sumarMes(fechaPagos,1);
        txtFechaEmision.setText(Integer.toString(fechaHoy.get(Calendar.DATE))+"/"+Integer.toString(fechaHoy.get(Calendar.MONTH))+"/"+ Integer.toString(fechaHoy.get(Calendar.YEAR)));
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtFechaEmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaEmisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaEmisionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbCuotas;
    private javax.swing.JComboBox<String> cmbDiaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtFechaEmision;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
