/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.*;
import accesoDatos.*;
import entidades.*;

/**
 *
 * @author Home
 */
public class JIFRegistroCliente extends javax.swing.JInternalFrame {    

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled); //To change body of generated methods, choose Tools | Templates.
    }
    
    static BaseDatosCliente cli = new BaseDatosCliente();
    
    ClienteNatural clicn=null;
    ClienteJuridico clicj=null;
    /**
     * Creates new form JIFRegistroCliente
     */
    public JIFRegistroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtClienteDNI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClienteNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtClienteTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtClienteDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtClienteCorreo = new javax.swing.JTextField();
        btnClienteIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtClienteLabor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtClientePerContacto = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Registro de Cliente");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Tipo:");

        lblCodigo.setText("DNI (8 dígitos):");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Telefono:");

        txtClienteTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteTelefonoActionPerformed(evt);
            }
        });

        jLabel5.setText("Dirección:");

        jLabel6.setText("Correo:");

        btnClienteIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Modificar.gif"))); // NOI18N
        btnClienteIngresar.setText("Ingresar");
        btnClienteIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteIngresarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/cancel.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural", "Juridico" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jLabel8.setText("Labor:");

        txtClienteLabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteLaborActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre Persona de Contacto:");

        txtClientePerContacto.setEnabled(false);
        txtClientePerContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientePerContactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(btnClienteIngresar)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigo)
                            .addComponent(jLabel1))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtClienteDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(txtClienteCorreo)
                                .addComponent(txtClienteNombre)
                                .addComponent(txtClienteTelefono)
                                .addComponent(txtClienteLabor)
                                .addComponent(txtClientePerContacto)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSalir)
                            .addGap(30, 30, 30)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClienteDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtClienteDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteLabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtClientePerContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnClienteIngresar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar(){
        txtClienteDNI.setText(null);
        txtClienteNombre.setText(null);
        txtClienteTelefono.setText(null);
        txtClienteDireccion.setText(null);
        txtClienteCorreo.setText(null);
        txtClienteLabor.setText(null);
        txtClientePerContacto.setText(null);
    }
    
    private void btnClienteIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteIngresarActionPerformed
        String nombre,telefono,direccion,correo,percon,labor;
        String dni = txtClienteDNI.getText();
        nombre = txtClienteNombre.getText();
        telefono = txtClienteTelefono.getText();
        direccion = txtClienteDireccion.getText();
        correo = txtClienteCorreo.getText();
        labor = txtClienteLabor.getText();
        percon = txtClientePerContacto.getText();
        int p=-1;
        if(nombre.length()!=0&&dni.length()!=0){
                for(int i=0;i<cli.getClientes().size();i++){
                        if(cli.getClientes().get(i).getCodigo().equals(dni)){
                            p=0;
                        }
                    }        

                if(cmbTipo.getSelectedItem()=="Natural"){

                    if(dni.length()==8){

                            if(p==-1){

                            clicn = new ClienteNatural(dni,nombre,telefono,direccion,correo,labor);
                            cli.agregarClienteN(clicn);
                            JOptionPane.showMessageDialog(this, "Cliente Natural registrado \n"+clicn.toString(), "Guardar", 1);
                            limpiar();

                            }
                            else{
                                JOptionPane.showMessageDialog(this, "El codigo (DNI) ingresado ya está registrado", "Regresar", 1);
                            }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Ingrese un DNI válido (8 dígitos)", "Regresar", 1);
                    }
                }
                else{
                    if(dni.length()==11){
                            if(p==-1){

                            clicj = new ClienteJuridico(dni,nombre,telefono,direccion,correo,percon);
                            cli.agregarClienteJ(clicj);
                            JOptionPane.showMessageDialog(this, "Cliente Juridico registrado \n"+clicj.toString(), "Guardar", 1);
                            limpiar();

                            }

                            else{
                                JOptionPane.showMessageDialog(this, "El codigo (RUC) ingresado ya está registrado", "Regresar", 1);
                            }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Ingrese un RUC válido (11 dígitos)", "Regresar", 1);
                    }
                }
        }
        else{
            JOptionPane.showMessageDialog(this, "Ingrese Datos requeridos para el registro (Código y Nombre)", "Regresar", 1);
        }
    }//GEN-LAST:event_btnClienteIngresarActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        
        if(cmbTipo.getSelectedItem()=="Juridico"){
            lblCodigo.setText("RUC \n(11 dígitos):");
            this.txtClientePerContacto.setEnabled(true);
            this.txtClienteLabor.setEnabled(false);
        }
        
        if(cmbTipo.getSelectedItem()=="Natural"){
            lblCodigo.setText("DNI \n(8 dígitos):");
            this.txtClientePerContacto.setEnabled(false);
            this.txtClienteLabor.setEnabled(true);
        }
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        JFMenu.vCli=false;
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtClienteTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteTelefonoActionPerformed

    private void txtClienteLaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteLaborActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteLaborActionPerformed

    private void txtClientePerContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientePerContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientePerContactoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        JFMenu.vCli=false;
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtClienteCorreo;
    private javax.swing.JTextField txtClienteDNI;
    private javax.swing.JTextField txtClienteDireccion;
    private javax.swing.JTextField txtClienteLabor;
    private javax.swing.JTextField txtClienteNombre;
    private javax.swing.JTextField txtClientePerContacto;
    private javax.swing.JTextField txtClienteTelefono;
    // End of variables declaration//GEN-END:variables
}
