/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Home
 */
public class JIFReporteClienteDeuda extends javax.swing.JInternalFrame {
    
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form JIFReporteClienteDeuda
     */
    public JIFReporteClienteDeuda() {
        initComponents();
        crearTabla();
        llenarTabla();
    }
    
    public void crearTabla(){
        modelo.addColumn("Tipo");
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Telefono");
        modelo.addColumn("Direccion");
        modelo.addColumn("Correo");
        modelo.addColumn("N° Cuotas");
        
        tblClientes.setModel(modelo);
    }
    
    public void limpiarTabla(){        
        int nf = modelo.getRowCount()-1;
        for (int i = nf; i >= 0; i--) {
            modelo.removeRow(modelo.getRowCount()-1);
        }
    }
    
    private void llenarTabla(){        
        Cliente c;
        Prestamo p;
        String dato[]= new String[7];
        
        for(int i=0;i<JIFRegistroPrestamo.BPres.getPrestamos().size();i++){
            if(JIFRegistroPrestamo.BPres.getPrestamos().get(i).isEstado()==false){
                p = JIFRegistroPrestamo.BPres.getPrestamos().get(i);
                c = p.getCliente();
                
                if(c.getCodigo().length()==8){
                    dato[0]= "N";
                }
                if(c.getCodigo().length()==11){
                    dato[0]= "J";
                }
                
                dato[1]= c.getCodigo();
                dato[2]= c.getNombre();
                dato[3]= c.getTelefono();
                dato[4]= c.getDireccion();
                dato[5]= c.getCorreo();
                dato[6]= String.valueOf(p.getNumeroDeCuotas());
                modelo.addRow(dato);
            }
                
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setClosable(true);
        setTitle("Reporte de Clientes con Prestamos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        JFMenu.vRepCliD=false;
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
