/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
import javax.swing.*;
import entidades.*;
import java.text.DecimalFormat;
import java.util.*;
/**
 *
 * @author Home
 */
public class JIFRegistroPago extends javax.swing.JInternalFrame {
    
    Cliente cl = null;
    Cuota c = null;
    Prestamo p = null;

    /**
     * Creates new form JIFRegistroPago
     */
    public JIFRegistroPago() {
        initComponents();
    }
    
    public void limpiar(){
        txtNCuota.setText(null);
        txtSaldo.setText(null);
        txtAmortizacion.setText(null);
        txtInteres.setText(null);
        txtCuota.setText(null);
        txtFechaVencimiento.setText(null);
        txtEstado.setText(null);
        txtPago.setText("0");
        txtNombres.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNCuota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAmortizacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtInteres = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaVencimiento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCuota = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPago = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtCajero = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Registro de Pagos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Codigo:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Buscar2.gif"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombres:");

        txtNombres.setBackground(new java.awt.Color(204, 204, 204));
        txtNombres.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombres.setDoubleBuffered(true);
        txtNombres.setEnabled(false);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/cancel.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de cuota"));

        jLabel3.setText("N° Cuota:");

        txtNCuota.setEnabled(false);

        jLabel4.setText("Saldo:");

        txtSaldo.setEnabled(false);

        jLabel5.setText("Amortización:");

        txtAmortizacion.setEnabled(false);

        jLabel6.setText("Interés:");

        txtInteres.setEnabled(false);

        jLabel7.setText("Fecha de Vencimiento:");

        txtFechaVencimiento.setEnabled(false);
        txtFechaVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaVencimientoActionPerformed(evt);
            }
        });

        jLabel8.setText("Estado:");

        txtEstado.setEnabled(false);

        jLabel10.setText("Cuota:");

        txtCuota.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(txtAmortizacion)
                    .addComponent(txtInteres))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAmortizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("Cantidad de pago:");

        txtPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagoActionPerformed(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/iconos/Modificar.gif"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel11.setText("Cajero:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addGap(130, 130, 130)
                                .addComponent(btnSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtCajero)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txtCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnRegistrar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String dni = txtDNI.getText();
        Cliente cliente=null;
        Prestamo prestamo;
        Cuota cuota;
        int k = -1;
        int m = -1;
        
        if(dni.length()!=0){

            for(int i=0;i<JIFRegistroCliente.cli.getCNaturales().size();i++){
                if(dni.equals(JIFRegistroCliente.cli.getCNaturales().get(i).getCodigo())){
                    txtNombres.setText(JIFRegistroCliente.cli.getCNaturales().get(i).getNombre());
                    cliente = JIFRegistroCliente.cli.getCNaturales().get(i);
                    cl = cliente;
                    m=0;
                }
            }

            for(int i=0;i<JIFRegistroCliente.cli.getCJuridicos().size();i++){
                if(dni.equals(JIFRegistroCliente.cli.getCJuridicos().get(i).getCodigo())){
                    txtNombres.setText(JIFRegistroCliente.cli.getCJuridicos().get(i).getNombre());
                    cliente = JIFRegistroCliente.cli.getCJuridicos().get(i);
                    cl = cliente;
                    m=0;
                }

            }
            
            if(m!=-1){
            
            for(int i=0;i<JIFRegistroPrestamo.BPres.getPrestamos().size();i++){
                if(cliente==JIFRegistroPrestamo.BPres.getPrestamos().get(i).getCliente()){
                    if(JIFRegistroPrestamo.BPres.getPrestamos().get(i).isEstado()==false){
                        k=i;
                    }
                }
            }
            
            try{
            if(k!=-1){
                
                prestamo = JIFRegistroPrestamo.BPres.getPrestamos().get(k);
                p = prestamo;
                int l = -1;
                
                for(int i=0;i<JIFGenerarCronograma.BCuota.getCuotas().size();i++){
                if(prestamo==JIFGenerarCronograma.BCuota.getCuotas().get(i).getPrestamo()){
                    if(JIFGenerarCronograma.BCuota.getCuotas().get(i).isEstadoCuota()==false){
                        l=i;
                        i=JIFGenerarCronograma.BCuota.getCuotas().size();
                    }
                }
                }
                
                cuota = JIFGenerarCronograma.BCuota.getCuotas().get(l);
                c = cuota;
                DecimalFormat df = new DecimalFormat("0.00");
                
                txtNCuota.setText(String.valueOf(cuota.getNumeroDeCuota()));
                txtSaldo.setText(String.valueOf(df.format(cuota.getSaldoRestante())));
                txtAmortizacion.setText(String.valueOf(df.format(cuota.getAmortizacion())));
                txtInteres.setText(String.valueOf(df.format(cuota.getInteres())));
                txtCuota.setText(String.valueOf(df.format(cuota.getCuota())));
                txtFechaVencimiento.setText(String.valueOf(cuota.getFechaVencimiento().toLocaleString()));
                txtEstado.setText("No Pagado");
            
            }
            else{
                JOptionPane.showMessageDialog(this, "El cliente no tiene un prestamo vigente", "Regresar", 1);
            }
            }
            catch(ArrayIndexOutOfBoundsException ex){
                JOptionPane.showMessageDialog(this, "El cliente no tiene un prestamo vigente", "Regresar", 1);
                limpiar();
            }
            }
            else{
                JOptionPane.showMessageDialog(this, "No hay un cliente registrado con este código", "Regresar", 1);
                limpiar();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese un codigo", "Regresar", 1);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        JFMenu.vPag=false;
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        JFMenu.vPag=false;
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtFechaVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaVencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaVencimientoActionPerformed

    private void txtPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try{
            Calendar fechaPago = Calendar.getInstance();
            fechaPago.add(Calendar.MONTH, 1);
            String dni = txtDNI.getText();
            float pago = Float.parseFloat(txtPago.getText());
            String cajero = txtCajero.getText();
            float resto;
            int k=-1;
            DecimalFormat df = new DecimalFormat("0.00");
            String ccc = String.valueOf(df.format(c.getCuota()));
            String pp = String.valueOf(df.format(pago));
            String ss = String.valueOf(df.format(c.getSaldoRestante()));
            int m=-1;
            
            if(dni.length()!=0){

                if(txtNombres.getText().length()!=0){

                    if(pago>0){
                        
                        if(!pp.equals(ss)){
                        
                            if(!pp.equals(ccc)){

                                resto = c.getCuota() - pago;
                                c.setEstadoCuota(true);

                                for(int i=0;i<JIFGenerarCronograma.BCuota.getCuotas().size();i++){
                                    if(p==JIFGenerarCronograma.BCuota.getCuotas().get(i).getPrestamo()){
                                        if(JIFGenerarCronograma.BCuota.getCuotas().get(i).isEstadoCuota()==false){
                                            k=i;
                                            i=JIFGenerarCronograma.BCuota.getCuotas().size();
                                        }
                                    }
                                }

                                if(k!=-1){
                                    JIFGenerarCronograma.BCuota.getCuotas().get(k).setCuota(JIFGenerarCronograma.BCuota.getCuotas().get(k).getCuota()+resto);
                                    Pago ppp = new Pago(fechaPago,fechaPago,pago,cajero,c);
                                    c.setPago(ppp);
                                    JOptionPane.showMessageDialog(this, "Pago registrado", "Regresar", 1);
                                    if(m==0){
                                        p.setEstado(true);
                                    }
                                    limpiar();
                                }
                                else{
                                    JOptionPane.showMessageDialog(this, "Requiere pagar la cuota completa", "Regresar", 1);
                                    m=0;
                                }
                            }

                            if(pp.equals(ccc)){
                                c.setEstadoCuota(true);
                                Pago ppp = new Pago(fechaPago,fechaPago,pago,cajero,c);
                                c.setPago(ppp);
                                JOptionPane.showMessageDialog(this, "Pago registrado", "Regresar", 1);
                                limpiar();
                            }
                        }
                        else{
                            p.setEstado(true);
                            JOptionPane.showMessageDialog(this, "Pago registrado", "Regresar", 1);
                            for(int i=0;i<JIFGenerarCronograma.BCuota.getCuotas().size();i++){
                                if(p==JIFGenerarCronograma.BCuota.getCuotas().get(i).getPrestamo()){
                                    if(JIFGenerarCronograma.BCuota.getCuotas().get(i).isEstadoCuota()==false){
                                        JIFGenerarCronograma.BCuota.getCuotas().get(i).setEstadoCuota(true);
                                    }
                                }
                            }
                            limpiar();
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Ingrese un pago válido", "Regresar", 1);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Ingrese un cliente", "Regresar", 1);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Ingrese un codigo", "Regresar", 1);
            }
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Ingrese un valores requeridos", "Regresar", 1);
            txtPago.setText("0");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        txtPago.setText("0");
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAmortizacion;
    private javax.swing.JTextField txtCajero;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtNCuota;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
